---

# https://docs.rke2.io/known_issues
- name: Configure NetworkManager to ignore RKE2 interfaces
  ansible.builtin.copy:
    src: NetworkManager/conf.d/rke2-canal.conf
    dest: /etc/NetworkManager/conf.d/rke2-canal.conf
    mode: 0644
  notify: Reload NetworkManager

- name: Tune fs.inotify.max_user_instances
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: '8192'
    state: present

# https://docs.rke2.io/known_issues
- name: Disable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: false
    state: stopped

- name: Install RKE2
  ansible.builtin.shell:
    cmd: "curl -sfL https://get.rke2.io | sh -"
    creates: /etc/rancher

- name: Configure RKE2 cluster IP
  ansible.builtin.template:
    src: rancher/rke2/config.yaml
    dest: /etc/rancher/rke2/config.yaml
    mode: 0644

- name: Start and Enable RKE2
  ansible.builtin.service:
    name: rke2-server
    state: started
    enabled: true

- name: Install Local Path Provisioner
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.28/deploy/local-path-storage.yaml
    kubeconfig: "{{ kubeconfig }}"
  register: result
  retries: 10
  delay: 10
  until: result.failed is not defined or result.failed == false

- name: Create /opt/local-path-provisioner
  ansible.builtin.file:
    path: /opt/local-path-provisioner
    state: directory

- name: Fix /opt/local-path-provisioner context for SELinux
  ansible.builtin.command: restorecon -rv /opt/local-path-provisioner

- name: Install NodePort Proxy for ingress
  import_tasks: nodeport_proxy.yaml
  when: nodeport_proxy | bool

- name: Install metallb for ingress
  import_tasks: metallb.yaml
  when: metallb | bool
