---

kubeconfig: /etc/rancher/rke2/rke2.yaml

# built-in defaults
fuzzball_orchestrate_defaults:
  apiVersion: deployment.ciq.com/v1alpha1
  kind: FuzzballOrchestrate
  metadata:
    labels:
      app.kubernetes.io/name: fuzzball-orchestrate
      app.kubernetes.io/part-of: fuzzball
      app.kubernetes.io/managed-by: ansible
    name: fuzzball-orchestrate
  spec:
    image:
      repository: "{{ depot_server }}/fuzzball/fuzzball-images"
      username: "{{ depot_user }}"
      password: "{{ depot_token }}"
      exclusive: false
    fuzzball:
      substrate:
        nfs:
          path: /srv/fuzzball/shared
          destination: /fuzzball/shared
      audit:
        storage:
          class: local-path
        localStorage: true
      log:
        storage:
          class: local-path
        serviceAccount: {}
      schedule:
        storage:
          class: local-path
        gossipService:
          type: NodePort
      dns:
        externalService:
          type: NodePort
      kube:
        backendGatewayService:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/allow-shared-ip: "ingress-and-fuzzball"
      storage:
        gossipService:
          type: NodePort
      workflow:
        callbackService:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/allow-shared-ip: "ingress-and-fuzzball"
    database:
      create:
        enableDebugPod: true
        storage:
          class: local-path
    kyverno:
      create: {}
    tls:
      certManager:
        create: {}
      trustManager:
        create: {}
    ingress:
      create:
        proxy:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/allow-shared-ip: "ingress-and-fuzzball"
    keycloak:
      create:
        createDatabase: true

# user-supplied values that will be recursively combined with
# fuzzball_orchestrate_defaults
fuzzball_orchestrate: {}
