---

- name: Deploy Fuzzball Orchestrate
  hosts: "{{ ansible_limit | default(omit) }}"
  pre_tasks:
  - name: Install python3-kubernetes for Ansible to use
    ansible.builtin.package:
      name: python3-kubernetes
      state: present
  - name: Install Helm
    ansible.builtin.shell:
      cmd: "curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -"
      creates: /usr/local/bin/helm
  roles:
  - ciq.fuzzball.fuzzball_orchestrate
